# JaCaMo Default log configuration
#
# Comment/uncomment the following lines to setup your log
#

# default Jason MAS Console GUI window and terminal console
handlers = jason.runtime.MASConsoleLogHandler, java.util.logging.ConsoleHandler

# Default logging level
.level = INFO

############################################################
# Handler specific properties.
############################################################

# Jason Handler parameters (MAS Console GUI)
jason.runtime.MASConsoleLogHandler.level = ALL
jason.runtime.MASConsoleLogHandler.formatter = jason.runtime.MASConsoleLogFormatter
# set one text area for each agent
jason.runtime.MASConsoleLogHandler.tabbed = true
jason.runtime.MASConsoleLogHandler.colors = true

# Limit the message that are printed on the terminal console to INFO and above.
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = jason.runtime.MASConsoleLogFormatter

java.level=OFF
javax.level=OFF
sun.level=OFF
jade.level=OFF
